dark_taurus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace='main'))
]

main/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name= 'main'

urlpatterns = [
    path('', views.userlogin, name='userlogin'),
    path('dashboard',views.dashboard, name='dashboard'),
    path('upload/<int:dept_id>',views.upload,name='upload'),
    path('orgdashboard/<int:dept_id>',views.Orgdashboard,name='orgdashboard'),
    path('view/<int:dept_id>',views.view,name='view'),
    path('settings',views.settings,name='settings'),
    path('logout',views.logout_view,name='logout'),
    path('usercreation',views.signup,name='usercreation'),
    path('userdepartmentmapping',views.userDepartmentMapping,name='userdepartmentmapping'),
    path('changepass',views.changepass,name='changepass'),
    path('usersettings',views.usersettings,name='usersettings'),
    path('userprofileupdate',views.userProfileUpdate,name="userprofileupdate"),
    path('deleteuser',views.deleteuser,name="deleteuser")
    
]


urlpatterns += staticfiles_urlpatterns()

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class Member(AbstractUser):
    phone = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return str(self.email)
        
class Department(models.Model):
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to="dept_logos/")

    def __str__(self):
        return str(self.name)
    
class DepartmentUserMapping(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    user = models.ForeignKey(Member, on_delete=models.CASCADE)
    is_approved = models.BooleanField(default=False)
    is_reviewed = models.BooleanField(default=False)
    class Meta:
        unique_together = ("user", "department")
    def __str__(self):
        return str(self.department) + " 's " + str(self.user)
    
class UploadedFile(models.Model):
    title = models.CharField(max_length=500)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    uploaded_by = models.ForeignKey(Member, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200,null=True,blank=True)
    file = models.FileField(upload_to='uploaded_files')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.department) + " 's " + str(self.uploaded_by) + " 's upload"

    def save(self, *args, **kwargs):
        if DepartmentUserMapping.objects.filter(user=self.uploaded_by, department=self.department, is_approved=True, is_reviewed=True).exists():

            return super().save(*args, **kwargs)
        else:
            raise Exception("User doesnt have permission to upload")

main/views.py
from typing import Reversible
from django.contrib.auth.hashers import check_password, make_password
from django.contrib.auth import authenticate, login, logout
from django.core.files.storage import FileSystemStorage
from django.shortcuts import redirect, render
from .models import Department, DepartmentUserMapping, UploadedFile, Member
 

def userlogin(request):
    if request.method == 'POST':
        # Process the request if posted data are available
        username = request.POST['username']
        password = request.POST['password']
        # Check username and password combination if correct
        print(username,password )
        user = authenticate(username=username, password=password)
        print(user)
        if user is not None:
            # Save session as cookie to login the user
            login(request, user)
            # Success, now let's login the user.
            return redirect('main:dashboard')
        else:
            # Incorrect credentials, let's throw an error to the screen.
            return render(request, 'index.html', {'error_message': 'Incorrect username and / or password.'})
    else:
        # No post data availabe, let's just show the page to the user.
        return render(request, 'index.html')


def dashboard(request):
    if request.method == "GET":
        context_user = request.user
        context_department = DepartmentUserMapping.objects.filter(user=context_user)
        # context_department_info =Department.objects.filter(name=context_department)
        context_uploadedfiles = UploadedFile.objects.filter(uploaded_by=context_user)
        context={
            "departments": context_department,
            # "departments_info": context_department_info,
            "uploaded_files":context_uploadedfiles,
        }
        print(context_department)
        return render(request,'dashboard.html',context)


def Orgdashboard(request,dept_id):
    if request.method == "GET":
        context_user = request.user
        context_department = DepartmentUserMapping.objects.filter(user=context_user)
        context_depart_name=depart_name = Department.objects.get(id=dept_id)
        context_uploadedfiles = UploadedFile.objects.filter(uploaded_by=context_user,department=context_depart_name)

        context={
            "departments": context_department,
            "filesuploadeds":context_uploadedfiles,
        }
        return render(request,'orgdash.html',context)


def upload(request,dept_id):
    print(dept_id)
    if request.method == "GET":
        context_user = request.user
        context_department = DepartmentUserMapping.objects.filter(user=context_user)
       
        context={
            "departments": context_department,
            "dept_id": dept_id 
        }
        return render(request,'upload.html',context)
    if request.method == "POST" and request.FILES['upload']:
        depart_name = Department.objects.get(id=dept_id)
        subject = request.POST.get('subject')
        comment = request.POST.get('comment')
        uploadfile = request.FILES['upload']
        fss = FileSystemStorage()
        file = fss.save(uploadfile.name, uploadfile)
        print(file)
        UploadedFile.objects.create(title=subject,department= depart_name,uploaded_by=request.user,comment=comment,file=file)
        return redirect('main:dashboard')

def view(request,dept_id):
    if request.method == "GET":
        context_user = request.user
        context_department = DepartmentUserMapping.objects.filter(user=context_user)
        context_uploadedfiles = UploadedFile.objects.filter(uploaded_by=context_user)

        context={
            "departments": context_department,
            "filesuploadeds":context_uploadedfiles,
        }
        return render(request,'orgview.html',context)

def settings(request):
    if request.method == "GET":
        context_user = request.user
        context_department = DepartmentUserMapping.objects.filter(user=context_user)
        context_alluser = Member.objects.all()
        context={
            "departments": context_department,
            "user":context_alluser
            # "filesuploadeds":context_uploadedfiles,
        }
        return render(request,'settings.html',context)


def logout_view(request):
    logout(request)
    return redirect('main:userlogin')

def userDepartmentMapping(request):
    if request.method == "POST":
        mapping_user = request.POST.get('userselected')
        mapping_dept = request.POST.get('departmentselected')
        print(mapping_user)
        print(mapping_dept)
       
        DepartmentUserMapping.objects.create(department_id=mapping_dept,user_id=mapping_user,is_approved = True,is_reviewed=True)
        return redirect('main:settings')

def signup(request):
    if request.method == "POST":
        if request.POST['password1'] == request.POST['password2'] :
            if (request.POST['role'] == 'user'):
                try:
                    Member.objects.get(username = request.POST['username'])
                    return render (request,'main:settings', {'error':'Username is already taken!'})
                except Member.DoesNotExist:
                    role=request.POST['role']
                    email=request.POST['email']
                    user = Member.objects.create_user(request.POST['username'],password=request.POST['password1'],email=email,is_active=True,is_staff=True,phone=request.POST['contactnumber'])
                    login(request,user)
                    return redirect('main:settings')
            else:
                try:
                    Member.objects.get(username = request.POST['username'])
                    return render (request,'main:settings', {'error':'Username is already taken!'})
                except Member.DoesNotExist:
                    role=request.POST['role']
                    email=request.POST['email']
                    user = Member.objects.create_user(request.POST['username'],password=request.POST['password1'],email=email,is_active=True,is_superuser=True,phone=request.POST['contactnumber'])
                    login(request,user)
                    return redirect('main:settings')
        else:
            return render (request,'main:settings', {'error':'Password does not match!'})
    else:
        return redirect('main:settings')


def changepass(request):
     if request.method == "POST":
        context_username = request.user 
        ex_password = request.POST.get('exisitngpass',None)
        new_password = request.POST.get('password1',None)
        new_confirm_password = request.POST.get('password2',None)
        print(new_confirm_password,new_password,ex_password)
        if context_username.check_password(ex_password)==True: 
            if new_password==new_confirm_password:
                context_username.set_password(new_confirm_password)
                context_username.save()
            return redirect('main:userlogin')
        else:
            return redirect('main:settings')
     else:
        return redirect('main:settings')


def usersettings(request):
    if request.method == "GET":
        context_user = request.user
        context_department = DepartmentUserMapping.objects.filter(user=context_user)
        context = {
            "loged_user": context_user,
            "departments": context_department,
        }
        return render(request,'usersettings.html',context)

def userProfileUpdate(request):
     if request.method == "POST":
        context_user  = request.user
        context_phone = request.POST.get('contactnumber')
        context_user.phone = context_phone
        context_user.save(update_fields=['phone'])
        print(context_user.phone)
     return redirect('main:userlogin')

def deleteuser(request):
    if request.method == "POST":
        context_user = request.user
        context_userselected = request.POST.get('userselected')
        context_user_for_inactive = Member.objects.get(id=context_userselected)
        context_user_for_inactive.is_active = False
        context_user_for_inactive.save()
        return redirect('main:dashboard')

main/templates/settings.html
{% extends 'base.html' %}
{% block 'nav' %}
    <nav id="mainNavbar" class="navbar navbar-vertical navbar-expand-lg scrollbar bg-dark navbar-dark">
                            
        <!-- Theme configuration (navbar) -->
            <script>
                let navigationColor = localStorage.getItem('navigationColor'),
                    navbar = document.getElementById('mainNavbar');
            
                if(navigationColor != null && navbar != null) {
                    if(navigationColor == 'inverted') {
                        navbar.classList.add('bg-dark', 'navbar-dark');
                        navbar.classList.remove('bg-white', 'navbar-light');
                    } else {
                        navbar.classList.add('bg-white', 'navbar-light');
                        navbar.classList.remove('bg-dark', 'navbar-dark');
                    }
                }
            </script>    
         <div class="container-fluid">
        
            <!-- Brand -->
            <a class="navbar-brand" href="#">
               <center> {% load static %}<img src="{% static 'images/vishal.png' %}"/> </center>
                <h4 style="color: white;">FILE MANAGEMENT SYSTEM</h4>
            </a>
    
            <!-- Navbar toggler -->
            <a href="javascript: void(0);" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#sidenavCollapse" aria-controls="sidenavCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </a>
    
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenavCollapse">
    
                <!-- Navigation -->
                <ul class="navbar-nav mb-lg-7">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'main:dashboard' %}" class="nav-link">
                            <span>Dashboards</span>
                        </a>
                    </li>
                    {% for department in departments %}
                        <li class="nav-item dropdown">
                            <a class="nav-link " href="#pagesCollapse{{ department.department.name }}" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="pagesCollapse">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="nav-link-icon" height="18" width="18"><defs><style>.a{fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:1.5px;}</style></defs><title>common-file-double-1</title><path class="a" d="M17.25,23.25H3.75a1.5,1.5,0,0,1-1.5-1.5V5.25"/><rect class="a" x="5.25" y="0.75" width="16.5" height="19.5" rx="1" ry="1"/></svg>
                                <span>{{ department.department.name }}</span>
                            </a>
                            <div class="collapse " id="pagesCollapse{{ department.department.name }}">
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <a href="{% url 'main:orgdashboard' department.department.id %}" class="nav-link ">
                                        Dashboard
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url 'main:upload' department.department.id %}" class="nav-link ">
                                        Upload
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url 'main:view' department.department.id %}" class="nav-link ">
                                        View
                                        </a>
                                    </li>
                                    
                                </ul>
                            </div>
                        </li>
                    
                    {% endfor %}
                    {% if request.user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'main:usersettings' %}">
                            <svg viewBox="0 0 24 24" class="nav-link-icon" height="18" width="18" xmlns="http://www.w3.org/2000/svg"><path d="M11.25,18.75a1.5,1.5,0,0,1-1.5-1.5V9.75a1.5,1.5,0,0,1,1.5-1.5h10.5a1.5,1.5,0,0,1,1.5,1.5v7.5a1.5,1.5,0,0,1-1.5,1.5h-1.5v4.5l-4.5-4.5Z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"/><path d="M6.75,12.75l-3,3v-4.5H2.25a1.5,1.5,0,0,1-1.5-1.5V2.25A1.5,1.5,0,0,1,2.25.75h10.5a1.5,1.5,0,0,1,1.5,1.5v3" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"/></svg>
                            <span>User Settings</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if request.user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'main:settings' %}">
                            <svg viewBox="0 0 24 24" class="nav-link-icon" height="18" width="18" xmlns="http://www.w3.org/2000/svg"><path d="M11.25,18.75a1.5,1.5,0,0,1-1.5-1.5V9.75a1.5,1.5,0,0,1,1.5-1.5h10.5a1.5,1.5,0,0,1,1.5,1.5v7.5a1.5,1.5,0,0,1-1.5,1.5h-1.5v4.5l-4.5-4.5Z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"/><path d="M6.75,12.75l-3,3v-4.5H2.25a1.5,1.5,0,0,1-1.5-1.5V2.25A1.5,1.5,0,0,1,2.25.75h10.5a1.5,1.5,0,0,1,1.5,1.5v3" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"/></svg>
                            <span>Settings</span>
                        </a>
                    </li>
                    {% endif %}
                   
                </ul>
                <!-- End of Navigation -->
           
            </div>
            <!-- End of Collapse -->
        </div>
    </nav>
    <br/>

{% endblock %}
{% block 'content' %}
    <div class="container" style="width: 60%; ">
        <form class="form-control sm" method="POST" action="{% url 'main:usercreation' %}"  enctype="multipart/form-data">
            {% csrf_token %}
            <h4>Add User</h4>
            <div class="mb-0">
                <label class="form-label" for="inputusername">User Name </label>
                <input type="text" class="form-control" id="inputusername" placeholder="Username" name="username" required>
            </div>
            <br/>
            <div class="mb-0">
                <label class="form-label" for="inputEmail">Email</label>
                <input type="email" class="form-control" id="inputEmail" placeholder="Email" name="email" required>
            </div>
            <br/>
            <div class="mb-0">
                <label class="form-label" for="inputEmail">Contact Number</label>
                <input type="number" class="form-control" id="inputEmail" placeholder="Mobile Number" name="contactnumber">
            </div>
            <br/>
            <div class="mb-0">
                <label class="form-label" for="inputuserorle">Role</label>
                <select class="form-select" aria-label="Default select example" name="role" required> 
                    <option value="user">User</option>
                    <option value="admin">Admin</option> 
                </select>
            
            </div>
            <br/>
            <br/>
            <div class="mb-0">
                <label class="form-label" for="inputpassword">Password</label>
                <input type="password" class="form-control" id="inputpassword" placeholder="Password"  name="password1" required>
            </div>
            <br/>
            <div class="mb-0">
                <label class="form-label" for="inputconfirmpassword">Confirm Password</label>
                <input type="password" class="form-control" id="inputconfirmpassword" placeholder="Email" name="password2" required>
            </div>
            <br/>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>

  <br/>

    <div class="container" style="width: 60%; ">
        <form class="form-control sm" method="POST" action="{% url 'main:userdepartmentmapping' %}"  enctype="multipart/form-data">
            {% csrf_token %}
            <h4>MAP User to Department</h4>
            <div class="mb-0">
                <label class="form-label" for="inputuserorle">Users</label>
                <select class="form-select" aria-label="Default select example" name="userselected" required> 
                    {% for i in user %}
                        <option value="{{  i.id }}">{{ i.username }}</option>
                    {% endfor %}
                </select>
            
            </div>
            <br/>

            <div class="mb-0">
                <label class="form-label" for="inputuserorle">Select Department To Add</label>
                <select class="form-select" aria-label="Default select example" name="departmentselected" required> 
                    {% for i in departments %}
                        <option value="{{ i.department.id }}">{{ i.department.name }}</option>
                    {% endfor %}
                </select>
            
            </div>
            <br/>
            
            <button type="submit" class="btn btn-primary">MAP</button>
        </form>
    </div>
    <br/>
    <div class="container" style="width: 60%; ">
        <form class="form-control sm" method="POST" action="{% url 'main:changepass' %}"  enctype="multipart/form-data">
            {% csrf_token %}
            <h4>Change Pass</h4>
            <div class="mb-0">
                <label class="form-label" for="inputuExisitngpass">Existing Password</label>
                <input type="password" class="form-control" id="inputuExisitngpass" placeholder="Exisitng Password" name="exisitngpass"  required>
            </div>
            <br/>
           
            <div class="mb-0">
                <label class="form-label" for="inputpassword">Password</label>
                <input type="password" class="form-control" id="inputpassword" placeholder="New Password"  name="password1" required>
            </div>
            <br/>
            <div class="mb-0">
                <label class="form-label" for="inputconfirmpassword">Confirm Password</label>
                <input type="password" class="form-control" id="inputconfirmpassword" placeholder="Confirm New Password" name="password2" required>
            </div>
            <br/>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>

    <br/>
    <div class="container" style="width: 60%; ">
        <form class="form-control sm" method="POST" action="{% url 'main:deleteuser' %}"  enctype="multipart/form-data">
            {% csrf_token %}
            <h4>Delete User</h4>
            <div class="mb-0">
                <label class="form-label" for="inputuserorle">Users</label>
                <select class="form-select" aria-label="Default select example" name="userselected" required> 
                    {% for i in user %}
                        <option value="{{  i.id }}">{{ i.username }}</option>
                    {% endfor %}
                </select>
            
            </div>
            <br/>
        
            <br/>
            <button type="submit" class="btn btn-primary">Delete</button>
        </form>
    </div>

{% endblock %}

main/templates/usersettings.html
{% extends 'base.html' %}
{% block 'nav' %}
    <nav id="mainNavbar" class="navbar navbar-vertical navbar-expand-lg scrollbar bg-dark navbar-dark">
                            
        <!-- Theme configuration (navbar) -->
            <script>
                let navigationColor = localStorage.getItem('navigationColor'),
                    navbar = document.getElementById('mainNavbar');
            
                if(navigationColor != null && navbar != null) {
                    if(navigationColor == 'inverted') {
                        navbar.classList.add('bg-dark', 'navbar-dark');
                        navbar.classList.remove('bg-white', 'navbar-light');
                    } else {
                        navbar.classList.add('bg-white', 'navbar-light');
                        navbar.classList.remove('bg-dark', 'navbar-dark');
                    }
                }
            </script>    
         <div class="container-fluid">
        
            <!-- Brand -->
            <a class="navbar-brand" href="#">
               <center> {% load static %}<img src="{% static 'images/vishal.png' %}"/> </center>
                <h4 style="color: white;">FILE MANAGEMENT SYSTEM</h4>
            </a>
    
            <!-- Navbar toggler -->
            <a href="javascript: void(0);" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#sidenavCollapse" aria-controls="sidenavCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </a>
    
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenavCollapse">
    
                <!-- Navigation -->
                <ul class="navbar-nav mb-lg-7">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'main:dashboard' %}" class="nav-link">
                            <span>Dashboards</span>
                        </a>
                    </li>
                    {% for department in departments %}
                        <li class="nav-item dropdown">
                            <a class="nav-link " href="#pagesCollapse{{ department.department.name }}" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="pagesCollapse">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="nav-link-icon" height="18" width="18"><defs><style>.a{fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:1.5px;}</style></defs><title>common-file-double-1</title><path class="a" d="M17.25,23.25H3.75a1.5,1.5,0,0,1-1.5-1.5V5.25"/><rect class="a" x="5.25" y="0.75" width="16.5" height="19.5" rx="1" ry="1"/></svg>
                                <span>{{ department.department.name }}</span>
                            </a>
                            <div class="collapse " id="pagesCollapse{{ department.department.name }}">
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <a href="{% url 'main:orgdashboard' department.department.id %}" class="nav-link ">
                                        Dashboard
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url 'main:upload' department.department.id %}" class="nav-link ">
                                        Upload
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url 'main:view' department.department.id %}" class="nav-link ">
                                        View
                                        </a>
                                    </li>
                                    
                                </ul>
                            </div>
                        </li>
                    
                    {% endfor %}
                    {% if request.user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'main:usersettings' %}">
                            <svg viewBox="0 0 24 24" class="nav-link-icon" height="18" width="18" xmlns="http://www.w3.org/2000/svg"><path d="M11.25,18.75a1.5,1.5,0,0,1-1.5-1.5V9.75a1.5,1.5,0,0,1,1.5-1.5h10.5a1.5,1.5,0,0,1,1.5,1.5v7.5a1.5,1.5,0,0,1-1.5,1.5h-1.5v4.5l-4.5-4.5Z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"/><path d="M6.75,12.75l-3,3v-4.5H2.25a1.5,1.5,0,0,1-1.5-1.5V2.25A1.5,1.5,0,0,1,2.25.75h10.5a1.5,1.5,0,0,1,1.5,1.5v3" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"/></svg>
                            <span>User Settings</span>
                        </a>
                    </li>
                    {% endif %}
                   
                </ul>
                <!-- End of Navigation -->
           
            </div>
            <!-- End of Collapse -->
        </div>
    </nav>
    <br/>

{% endblock %}
{% block 'content' %}
<div class="container"style="width: 60%; ">
    <form class="form-control sm"  method="POST" action="{% url 'main:userprofileupdate' %}"   enctype="multipart/form-data">
        {% csrf_token %}
        <h4>Update User</h4>
        <div class="mb-0">
            <label class="form-label" for="inputusername"> User Name</label>
            <input type="text" class="form-control" id="inputusername" placeholder="Username" name="username" value=" {{ request.user.username }}  " readonly>
        </div>
        <br/>
        <div class="mb-0">
            <label class="form-label" for="inputEmail">Email</label>
            <input type="email" class="form-control" id="inputEmail" placeholder="Email" name="email"  value=" {{ request.user.email }}  " readonly>
        </div>
        <br/>
        <div class="mb-0">
            <label class="form-label" for="inputphone">Contact Number</label>
            <input type="number" class="form-control" id="inputEmail" placeholder="Mobile Number" name="contactnumber"  required>
        </div>
        <br/>
         
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

<br/>

<div class="container" style="width: 60%; ">
    <form class="form-control sm" method="POST" action="{% url 'main:changepass' %}"  enctype="multipart/form-data">
        {% csrf_token %}
        <h4>Change Pass</h4>
        <div class="mb-0">
            <label class="form-label" for="inputuExisitngpass">Existing Password</label>
            <input type="password" class="form-control" id="inputuExisitngpass" placeholder="Exisitng Password" name="exisitngpass"  required>
        </div>
        <br/>
       
        <div class="mb-0">
            <label class="form-label" for="inputpassword">Password</label>
            <input type="password" class="form-control" id="inputpassword" placeholder="New Password"  name="password1" required>
        </div>
        <br/>
        <div class="mb-0">
            <label class="form-label" for="inputconfirmpassword">Confirm Password</label>
            <input type="password" class="form-control" id="inputconfirmpassword" placeholder="Confirm New Password" name="password2" required>
        </div>
        <br/>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}